apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ko6reaesq-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ko6reaesq-dotnet-basic-gitops